[[constraint]]
  branch = "master"
  name = "github.com/augustoroman/promise"

[[constraint]]
  branch = "master"
  name = "github.com/gopherjs/gopherjs"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "honnef.co/go/js/xhr"

[prune]
  go-tests = true
  unused-packages = true
