name: examples.hacker_news_pwa

environment:
  sdk: ">=2.0.0-dev.69.5 <3.0.0"

web:
  compiler:
    debug: dartdevc

dependencies:
  # No strict dependencies, we always use dependency_overrides.
  angular:
  angular_router:
  pwa: ^0.1.10
  hackernews: any

dev_dependencies:
  # No strict dependencies, we always use dependency_overrides.
  angular_test:
  build_runner: ^0.10.0
  build_test: ^0.10.2+5
  build_web_compilers: ^0.4.0+4
  pageloader: ^3.0.0-beta
  test: ^1.3.0

dependency_overrides:
  hackernews:
    path: ../hackernews/dart
