name: examples.hacker_news_pwa
environment:
  sdk: ">=2.0.0-dev.46.0 <2.0.0"

web:
  compiler:
    debug: dartdevc

dependencies:
  angular: ^5.0.0-alpha
  angular_router: ^2.0.0-alpha
  pwa: ^0.1.10
  hackernews: any

dev_dependencies:
  build_runner: ^0.8.0
  build_test: ^0.10.1+1
  build_web_compilers: ^0.3.4+1

dependency_overrides:
  hackernews:
    path: ../hackernews/dart
